"""
build_db.py — Compile operations_trending.db (SQLite) from a v12-shaped JSON snapshot.
This is the SEED step: it loads the current computed dashboard data into the DB as the
source of truth. Going forward, raw monthly exports populate the *_raw / sales_monthly
tables and a transform step (see README) refreshes the derived tables.

Usage:  python build_db.py [v12_data.json] [operations_trending.db]
"""
import json, sqlite3, sys, os

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, 'v12_data.json')
DB  = sys.argv[2] if len(sys.argv) > 2 else os.path.join(HERE, 'operations_trending.db')

METRICS = ['SOS','Window Time','OSAT','Accuracy','Complaints/10K',
           'Cert SL/AGM','Training','Hourly TO','COGS Var','Labor Var']

stores = json.load(open(SRC))['stores']
con = sqlite3.connect(DB); cur = con.cursor()
cur.executescript("""
DROP TABLE IF EXISTS store_master;
DROP TABLE IF EXISTS store_snapshot;
DROP TABLE IF EXISTS metric_score;
DROP TABLE IF EXISTS store_period;
DROP TABLE IF EXISTS cc_event;
DROP TABLE IF EXISTS gm_timeline;
DROP TABLE IF EXISTS sales_monthly;      -- raw input (future feed)
DROP TABLE IF EXISTS ops_metric_monthly; -- raw input (future feed)

-- ============ DIMENSION ============
CREATE TABLE store_master(
  pc INTEGER PRIMARY KEY, name TEXT, market TEXT, dm TEXT, rd TEXT, format TEXT, lat REAL, lon REAL);

-- ============ DERIVED / SNAPSHOT (seeded from v12; regenerated by transform) ============
CREATE TABLE store_snapshot(
  pc INTEGER PRIMARY KEY, category TEXT,
  actual_sss REAL, baseline_sss REAL, net_drag REAL, ext_count INTEGER,
  new_gg REAL, old_gg REAL, sales_4w REAL, annual_sales REAL,
  n_events INTEGER, weakest TEXT,
  current_gm TEXT, gm_changes INTEGER, gm_tenure REAL,
  FOREIGN KEY(pc) REFERENCES store_master(pc));

CREATE TABLE metric_score(
  pc INTEGER, metric TEXT, score REAL, raw_value REAL,
  PRIMARY KEY(pc, metric), FOREIGN KEY(pc) REFERENCES store_master(pc));

CREATE TABLE store_period(
  pc INTEGER, period TEXT, gg REAL, sss REAL, drag REAL, pf_sss REAL,
  PRIMARY KEY(pc, period), FOREIGN KEY(pc) REFERENCES store_master(pc));

CREATE TABLE cc_event(
  id INTEGER PRIMARY KEY AUTOINCREMENT, pc INTEGER,
  new_store TEXT, event_type TEXT, date_opened TEXT,
  impact REAL, net REAL, src TEXT, FOREIGN KEY(pc) REFERENCES store_master(pc));

CREATE TABLE gm_timeline(
  id INTEGER PRIMARY KEY AUTOINCREMENT, pc INTEGER,
  gm TEXT, start TEXT, end TEXT, FOREIGN KEY(pc) REFERENCES store_master(pc));

-- ============ RAW INPUT TABLES (empty until monthly feeds land) ============
CREATE TABLE sales_monthly(
  pc INTEGER, period TEXT, sales REAL, sales_py REAL,
  PRIMARY KEY(pc, period));
CREATE TABLE ops_metric_monthly(
  pc INTEGER, period TEXT, metric TEXT, raw_value REAL,
  PRIMARY KEY(pc, period, metric));
""")

for s in stores:
    cur.execute("INSERT INTO store_master VALUES(?,?,?,?,?,?,?,?)",
        (s['pc'], s['name'], s['market'], s['dm'], s['rd'], s['format'], s.get('lat'), s.get('lon')))
    cur.execute("INSERT INTO store_snapshot VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",
        (s['pc'], s.get('category'), s['actual_sss'], s['baseline_sss'], s['net_drag'],
         s.get('ext_count',0), s['new_gg'], s['old_gg'], s['sales_4w'], s['annual_sales'],
         s.get('n_events',0), s['weakest'], s['current_gm'], s['gm_changes'], s['gm_tenure']))
    for m in METRICS:
        cur.execute("INSERT INTO metric_score VALUES(?,?,?,?)",
            (s['pc'], m, s['metrics'].get(m), s.get('metric_values',{}).get(m)))
    for t in s['trend']:
        cur.execute("INSERT INTO store_period VALUES(?,?,?,?,?,?)",
            (s['pc'], t['period'], t.get('gg'), t.get('sss'), t.get('drag'), t.get('pf_sss')))
    for e in (s.get('events') or []):
        cur.execute("INSERT INTO cc_event(pc,new_store,event_type,date_opened,impact,net,src) VALUES(?,?,?,?,?,?,?)",
            (s['pc'], e.get('new_store'), e.get('event_type'), e.get('date_opened'),
             e.get('impact'), e.get('net'), e.get('src')))
    for g in (s.get('gm_timeline') or []):
        cur.execute("INSERT INTO gm_timeline(pc,gm,start,end) VALUES(?,?,?,?)",
            (s['pc'], g.get('gm'), g.get('start'), g.get('end')))

con.commit()
n = lambda q: cur.execute(q).fetchone()[0]
print('DB built:', DB)
print('  stores       :', n("SELECT COUNT(*) FROM store_master"))
print('  snapshot rows:', n("SELECT COUNT(*) FROM store_snapshot"))
print('  metric rows  :', n("SELECT COUNT(*) FROM metric_score"))
print('  period rows  :', n("SELECT COUNT(*) FROM store_period"))
print('  cc events    :', n("SELECT COUNT(*) FROM cc_event"))
print('  gm timeline  :', n("SELECT COUNT(*) FROM gm_timeline"))
con.close()
